# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google_scanned_objects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgoogle_scanned_objects.proto\"%\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\"8\n\rCompatibility\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x07version\x18\x02 \x01(\x0b\x32\x08.Version\":\n\nCategories\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0e\n\x06second\x18\x02 \x01(\t\x12\r\n\x05third\x18\x03 \x01(\t\"(\n\nAnnotation\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"+\n\x05Legal\x12\x11\n\tcopyright\x18\x01 \x01(\t\x12\x0f\n\x07license\x18\x02 \x01(\t\"\x19\n\tModelInfo\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"\xf6\x01\n\x08Metadata\x12\x19\n\x05model\x18\x01 \x01(\x0b\x32\n.ModelInfo\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x18\n\x07\x61uthors\x18\x05 \x03(\x0b\x32\x07.Author\x12\x15\n\x05legal\x18\x06 \x01(\x0b\x32\x06.Legal\x12 \n\x0b\x61nnotations\x18\x07 \x03(\x0b\x32\x0b.Annotation\x12\'\n\x0f\x63ompatibilities\x18\x08 \x01(\x0b\x32\x0e.Compatibility\x12\x1f\n\ncategories\x18\t \x01(\x0b\x32\x0b.Categoriesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google_scanned_objects_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHOR._serialized_start=32
  _AUTHOR._serialized_end=69
  _VERSION._serialized_start=71
  _VERSION._serialized_end=125
  _COMPATIBILITY._serialized_start=127
  _COMPATIBILITY._serialized_end=183
  _CATEGORIES._serialized_start=185
  _CATEGORIES._serialized_end=243
  _ANNOTATION._serialized_start=245
  _ANNOTATION._serialized_end=285
  _LEGAL._serialized_start=287
  _LEGAL._serialized_end=330
  _MODELINFO._serialized_start=332
  _MODELINFO._serialized_end=357
  _METADATA._serialized_start=360
  _METADATA._serialized_end=606
# @@protoc_insertion_point(module_scope)
