env:
  frame: world
  sim: gazebo
  interface: moveit
  verbose: false
  extra_objects:
    - cabinet.drawer0
    - cabinet.drawer1
    - cabinet.drawer2
    - cabinet.drawer3
    - cabinet.handle_0
    - cabinet.handle_1
    - cabinet.handle_2
    - cabinet.handle_3
  sensor:
    namespace: ''
    cameras: [camera_left, camera_right, camera_top]
    gt_point_cloud: false
  moveit_config:
    arm_base_link: panda_link0
    arm_group_name: panda_arm
    gripper_group_name: panda_hand
    manipulator_group_name: panda_manipulator
    use_gt_perception: false
    debug: true
    planning_time: 15
    max_velocity: 0.2
    max_acceleration: 0.2
    goal_position_tolerance: 0.001
    goal_orientation_tolerance: 0.02
    refenrence_frame: world
    cartesian_path: true
    initial_joint_values: [0.0, -0.7854, 0.0, -2.3562, 0.0, 1.5708, 0.7854]

grounding_model:
  model_name: glip
  model_args: {}
  
joint_predction:
  method: ground_truth
  model_params:
    service_name: /gazebo/get_joints_axes

grasp_detection:
  model_name: anygrasp
  model_params:
    service_name: /detect_grasps
  visualize: false
  verbose: false

plane_detection:
  model_name: open3d
  model_params: {}



lmps:
  tabletop_ui:
    class: LMPOpenAI
    model: gpt-3.5-turbo-16k
    messages: message_tabletop_text

    max_tokens: 2048
    temperature: 0
    query_prefix: '# '
    query_suffix: '.'
    maintain_session: false
    debug_mode: false
    include_context: true
    has_return: false
    return_val_name: ret_val
  fgen:
    class: LMPFGenOpenAI
    model: gpt-3.5-turbo-16k
    messages: message_fgen
    max_tokens: 2048
    temperature: 0
    query_prefix: '# define function: '
    query_suffix: '.'
    maintain_session: false
    debug_mode: false
    include_context: true
  parse_question:
    class: GroundingEmbodiedGPT
    model: gpt-3.5-turbo-16k
    messages: message_parse_question
    max_tokens: 2048
    temperature: 0
    query_prefix: '# '
    query_suffix: '.'
    maintain_session: false
    debug_mode: false
    include_context: true
    has_return: true
    return_val_name: ret_val