base_config: text_base.yaml

grounding_model: {} # not used in text-only setting

grasp_detection:
  model_name: anygrasp
  model_params:
    service_name: /detect_grasps
  visualize: false
  verbose: false

lmps:
  tabletop_ui:
    class: LMPOpenAI
    model: gpt-4
    messages: message_tabletop_text_few_shot
  
  fgen:
    class: LMPFGenOpenAI
    model: gpt-4 
    messages: message_fgen_few_shot
